name: Doc Publish
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Toolchain
        uses: xmc-rs/toolchain@v1.0.0
        with:
          toolchain: 'stable'
          target: 'x86_64-unknown-linux-gnu'
      - name: Cargo Doc
        uses: xmc-rs/cargo@v1.0.0
        with:
          command: doc
          args: --verbose --no-deps --document-private-items
