on:
  workflow_dispatch:
    inputs:
      version:
          description: Version to release
          required: true
          type: string

permissions:
  # TODO: once `releases: write` is supported, use it instead.
  contents: write

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-release
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions-rs/cargo@v1
        with:
          command: release
          args: ${{ inputs.version }} -x --no-confirm
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
